In [2]:
# Imports
import torch
import torch.nn as nn
import pandas as pd

In [3]:
sentiments = {
    "LABEL_0": "Bearish",
    "LABEL_1": "Bullish", 
    "LABEL_2": "Neutral"
}

In [4]:
# Load Train and Valid

train = pd.read_csv("sent_train.csv")
valid = pd.read_csv("sent_valid.csv")

In [6]:
# Check the are loaded correctly

display(train.head())
display(valid.head())

                                                text  label
0  $BYND - JPMorgan reels in expectations on Beyo...      0
1  $CCL $RCL - Nomura points to bookings weakness...      0
2  $CX - Cemex cut at Credit Suisse, J.P. Morgan ...      0
3  $ESS: BTIG Research cuts to Neutral https://t....      0
4  $FNKO - Funko slides after Piper Jaffray PT cu...      0

                                                text  label
0  $ALLY - Ally Financial pulls outlook https://t...      0
1  $DELL $HPE - Dell, HPE targets trimmed on comp...      0
2  $PRTY - Moody's turns negative on Party City h...      0
3                   $SAN: Deutsche Bank cuts to Hold      0
4                  $SITC: Compass Point cuts to Sell      0